<?php

namespace App\Command;


use App\Modules\ApiModule\Model\User\Connector\TwitchUserConnectFacade;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class RefreshTwitchSubscriptions extends Command
{

    public function __construct(
        private readonly TwitchUserConnectFacade $twitchUserConnectFacade,
    )
    {
        parent::__construct('refresh-twitch-subscriptions');
    }

    public function run(InputInterface $input, OutputInterface $output): int
    {
        return parent::run($input, $output); // TODO: Change the autogenerated stub
    }
}