<?php

namespace App\Modules\AdminModule\Component\Settings;

use App\Repository\Primary\SettingsRepository;
use Nette\Localization\Translator;
use Ublaboo\DataGrid\DataGrid;
use Ublaboo\DataGrid\Exception\DataGridException;

class SettingsGrid extends DataGrid
{
    public function __construct(
        private SettingsRepository $settingRepository,
        Translator                 $translator,
    ) {
        parent::__construct(null, 'settings');
        $this->translator = $translator;
    }

    /**
     * @return void
     * @throws DataGridException
     */
    public function render(): void
    {
        $this->setDataSource($this->settingRepository->findAll(true));

        $this->addColumnText(SettingsRepository::COLUMN_NAME, $this->translator->translate('admin.settings.field.name'))
            ->setFilterText([SettingsRepository::COLUMN_NAME]);

        $this->addColumnText(SettingsRepository::COLUMN_CONTENT, $this->translator->translate('admin.settings.field.content'));

        $this->addAction("edit", '', "Settings:edit", ['id' => 'id'])
            ->setClass('btn btn-sm btn-warning')
            ->setIcon('pen');

        $this->addToolbarButton("Settings:add", '')
            ->setClass("btn btn-sm btn-success")
            ->setIcon("plus");

        parent::render(); // TODO: Change the autogenerated stub
    }
}

interface ISettingsGridFactory
{
    /**
     * @return SettingsGrid
     */
    public function create(): SettingsGrid;
}
