<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="BeastBlock.cz | ERROR" property="og:title"/>
    <meta content="Zadrž! Tahle stránka není k dispozici nebo neexistuje. Jsi si jist, že to tu někdy bylo?" property="og:description"/>
    <meta content="https://beastblock.cz/" property="og:url"/>
    <meta content="{$basepath}/img/bestblock_icon_website.png" property="og:image"/>
    <meta content="#ff053b" data-react-helmet="true" name="theme-color"/>
    <meta name="author" content="Quaky & Caidorn & sCrapy">
    <meta name="project" content="BeastBlock.cz">
    <meta name="robots" content="noindex">

    <link rel="apple-touch-icon" sizes="180x180" href="{$basePath}/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="{$basePath}/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="{$basePath}/favicon/favicon-16x16.png">
    <link rel="manifest" href="{$basePath}/favicon/site.webmanifest">
    <link rel="mask-icon" href="{$basePath}/favicon/safari-pinned-tab.svg" color="#5bbad5">

    <link rel="stylesheet"
          href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Chyba serveru</title>
</head>
<body>
<style>
    body {
        background-image: url("/img/bg.jpg");
        background-repeat: no-repeat;
        background-size: cover;
        background-color: #161a1d;
    }

    a {
        color: orange;
    }

    a:hover {
        color: #bb7e09;
    }

    .container {
        padding-top: 10em;
    }

    .card {
        background-color: rgba(0,0,0,0.3);
        padding: 2em;
        color: white;
        border: 2px solid orange;
    }


</style>
<div class="container" style="text-align: center;">
    <img src="/img/Nakashi.png" alt="nakashi" height="300px">
    <div class="card">
        <h2>Údržba</h2>
        <p>Omlouváme se, aktuálně probíhá údržba webu. Opakujte akci později.</p>
        <p>Děkujeme za pochopení.</p>
    </div>

</div>
</body>
</html>