<?php

namespace App\Modules\WebModule\Presenter\Base;

use App\Repository\Primary\SettingsRepository;
use Contributte\Translation\Translator;
use Nette\Application\UI\Presenter;

class BasePresenter extends Presenter {
    /** @persistent */
    public $locale;

    /** @var Translator @inject */
    public $translator;

    protected SettingsRepository $settingRepository;

    /**
     * @param SettingsRepository $settingRepository
     * @return void
     */
    public function injectDependencies
    (
        SettingsRepository $settingRepository
    ): void
    {
        $this->settingRepository = $settingRepository;
    }

    protected function startup() {
        parent::startup();
        $this->template->setTranslator($this->translator);

    }

    public function checkRequirements($element): void
    {
        $this->getUser()->getStorage()->setNamespace('web');
        parent::checkRequirements($element); // TODO: Change the autogenerated stub
    }

    protected function beforeRender()
    {
        $this->template->hosting = $this->settingRepository->getSettingValue('hosting');
        $this->template->hostingUrl = $this->settingRepository->getSettingValue('hosting-url');
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }

}