<?php

namespace App\Modules\WebModule\Component\Positions;

use App\Component\BaseComponent;
use App\Repository\Primary\PositionRepository;

class PositionsListing extends BaseComponent
{
    public function __construct(
        private PositionRepository $positionRepository
    )
    {
    }

    public function render(): void
    {
        $this->template->positions = $this->positionRepository->getActive();
        parent::render(); // TODO: Change the autogenerated stub
    }
}