<?php

namespace App\FrontModule\Presenter;

use App\FrontModule\Component\ITeamFactory;
use App\FrontModule\Presenter\Base\BasePresenter;
use App\Repository\UserDetailsRepository;
use App\Repository\UserRoleRepository;
use Nette\Application\UI\Presenter;
use Nette\Localization\Translator;

class AboutPresenter extends BasePresenter
{

    private UserRoleRepository $userRoleRepository;
    private UserDetailsRepository $userDetailsRepository;
    private ITeamFactory $teamFactory;

    public function __construct(
        UserRoleRepository $userRoleRepository,
        UserDetailsRepository $userDetailsRepository,
        ITeamFactory $teamFactory
    ) {
        $this->userRoleRepository = $userRoleRepository;
        $this->userDetailsRepository = $userDetailsRepository;
        $this->teamFactory = $teamFactory;
    }

    protected function startup() {
        parent::startup(); // TODO: Change the autogenerated stub
        $this->template->setTranslator($this->translator);
    }


    public function createComponentTeam() {
        return $this->teamFactory->create();
    }
}