<?php

namespace App\Modules\ApiModule\Presenter;

use Nette\Application\AbortException;
use Nette\Application\Responses\JsonResponse;
use Nette\Application\UI\Presenter;
use Nette\Http\IResponse;
use Nette\Http\Response;
use Nette\Utils\Json;
use Nette\Utils\JsonException;

abstract class ApiPresenter extends Presenter
{
    protected function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
    }


    /**
     * @param array $data
     * @param int $code
     * @param string|null $message
     * @return void
     * @throws AbortException
     */
    protected function sendJsonWithCode(array $data, int $code = IResponse::S200_OK, ?string $message = null): void
    {
        $this->getHttpResponse()->setCode($code, $message);

        $response = new JsonResponse($data);
        $this->sendResponse($response);
    }
}
